# This file was generated by GoReleaser. DO NOT EDIT.
class Keto < Formula
  desc ""
  homepage "https://www.ory.sh"
  version "0.5.7-alpha.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ory/keto/releases/download/v0.5.7-alpha.1/keto_0.5.7-alpha.1_macOS_64-bit.tar.gz"
    sha256 "2ae8189003f195e5c1b4597c84ff41bd87fca05cb35127baa476bc44608861cb"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/ory/keto/releases/download/v0.5.7-alpha.1/keto_0.5.7-alpha.1_linux_64-bit.tar.gz"
      sha256 "3ddf7703f5fa0497801c75262664e932eb177cdb9e5f07e406eb6cee56d10112"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ory/keto/releases/download/v0.5.7-alpha.1/keto_0.5.7-alpha.1_linux_arm64.tar.gz"
        sha256 "7ddf822bdf751d66f90d61b37f935ad4bc1ad3c64ba5ba465eaae8c5f1e6ca62"
      else
        url "https://github.com/ory/keto/releases/download/v0.5.7-alpha.1/keto_0.5.7-alpha.1_linux_armv6.tar.gz"
        sha256 "8deef359ef847614e4071a5dbe0aace7cdca95197a62a2df89a673d099201355"
      end
    end
  end

  def install
    bin.install "keto"
  end
end
